language: python
matrix:
  include:
  - python: 3.6
    env:
      - LABEL=docker_unit_tests
    services:
      - docker
    script:
      - make build
      - make test-tox
      - docker run -it mozilla/vautomator-standalone python3 -m pytest ./tests/
