version: '3'
services:
  vautomator:
    # This does not work for some reason
    # sysctls:
    #  - net.ipv6.conf.all.disable_ipv6=0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TENABLEIO_ACCESS_KEY=${TENABLEIO_ACCESS_KEY}
        - TENABLEIO_SECRET_KEY=${TENABLEIO_SECRET_KEY}
    image: vautomator
